fix(refs DPLAN-16623): fix editing of segments (5283)
* add uploader and adjust styling

* add import center

* BMDS-3870: add options to delete segments (5239)

* BMDS-3870: add options to delete segments

* style: Apply php-cs-fixer

* BMDS-3870: handle procedure nullSafe

---------

Co-authored-by: Demos-CI <devops-system+github@demos-deutschland.de>

* adjust design of the header

* add DeHeader component to the project bundles

* chore(refs DPLAN-16623): fix some things after merge

most notably, the statement id instead of the externId
is now stored in StatementList > selectedRows, so navigating
to the segment management view was broken

* chore(refs DPLAN-16623): remove non-existent size

size="md" does not exist, there's a warning in the console

* fix(refs DPLAN-16623): avoid prosemirror version mismatch

we need to set the resolutions to the same versions we
use in demosplan-ui, otherwise there can be a version
mismatch that can lead to errors (in this case, when trying
to edit the range of a segment, there was this error:
Uncaught TypeError: style.eq is not a function
    at eval (index.js:952:53)
    at Fragment.nodesBetween (index.js:105:31)
    at Node.nodesBetween (index.js:1242:22)
    at Fragment.nodesBetween (index.js:107:23)
    at Node.nodesBetween (index.js:1242:22)
    at removeMark (index.js:927:12)
    at Transaction.removeMark (index.js:2161:9)
    at removeRange (commands.js:111:29)
so saving the changes was not possible

---------

Co-authored-by: Natalija Sakuta <sakuta@demos-deutschland.de>
Co-authored-by: MoritzMandler <89914798+MoritzMandler@users.noreply.github.com>
Co-authored-by: Demos-CI <devops-system+github@demos-deutschland.de>
Co-authored-by: riechedemos <carolin@demos-international.com>