Feat(refs: T32012): Change v-if logic, depending on the parent template/div and child template/div
Error:
Build encountered errors
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
Error: Codegen node is missing for element/if/for node. Apply appropriate transforms first.

Solution: using v-if instead of v-if-else multiple times for this works