Feat(refs: T32012): For now put the import of swagger-ui.css in a comment to evacuate the error
Error:
Module Error (from ./node_modules/vue-loader/dist/index.js):

VueCompilerError: Element is missing end tag.
at /srv/www/node_modules/swagger-ui-dist/swagger-ui.css:1:55
1  |  // style-loader: Adds some css to the DOM by adding a <style> tag
   |                                                        ^
2  |
3  |  // load the styles

There is an error with the vue-loader.
For now there is no other solution.
Its just a solution for now to evacuate the error.