Feat(refs: T32012): add the key in the template tag, not to the children. change the structure and remove child tags if not needed and put the key to the parent tag always
Error:
Module Error (from ./node_modules/vue-loader/dist/templateLoader.js):

VueCompilerError: <template v-for> key should be placed on the <template> tag.

Solution: <template v-for> key should be placed on the <template> tag (rather than on its children).

in DpTable.vue is added ref="root". Vue3 components are no longer limited to only 1 root element.
you have to use ref to interact with any element in the template.

In the setup function, you should instantiate root as const root = ref(null).
In the Options API, you can just use this.$refs.root in any method or hook, as long as it's after mounted().