fix(refs DPLAN-16623): avoid prosemirror version mismatch
we need to set the resolutions to the same versions we
use in demosplan-ui, otherwise there can be a version
mismatch that can lead to errors (in this case, when trying
to edit the range of a segment, there was this error:
Uncaught TypeError: style.eq is not a function
    at eval (index.js:952:53)
    at Fragment.nodesBetween (index.js:105:31)
    at Node.nodesBetween (index.js:1242:22)
    at Fragment.nodesBetween (index.js:107:23)
    at Node.nodesBetween (index.js:1242:22)
    at removeMark (index.js:927:12)
    at Transaction.removeMark (index.js:2161:9)
    at removeRange (commands.js:111:29)
so saving the changes was not possible